import { useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { categories, experiences } from './data/seed'
import type { Category, Experience } from './types'
import { getLocal, saveLocal } from './lib/storage'

type Page = 'home' | 'user' | 'business' | 'driver' | 'admin'
type PhoneTab = 'mapa' | 'evento' | 'transporte' | 'perfil' | 'agenda' | 'beneficios'

type PartnerForm = { name: string; category: string; instagram: string; address: string; phone: string }
type DriverForm = { name: string; phone: string; vehicle: string; plate: string; city: string }

const categoryIcon: Record<Category, string> = {
  Bombando: '🔥',
  'Musica ao vivo': '🎶',
  Gastronomia: '🍽️',
  Cultural: '🎭',
  'Modo Relax': '🌙',
  'Ambiente infantil': '🧸'
}
const reactions = ['Bombando 🔥', 'Energia Alta ⚡', 'Acolhedor 💜', 'Seguro 🛡️', 'Público Incrível ✨', 'Atendimento Top 👏']

export default function AppV8() {
  const [page, setPage] = useState<Page>('home')
  const [category, setCategory] = useState<Category>('Bombando')
  const [query, setQuery] = useState('Will, onde é hoje?')
  const [tab, setTab] = useState<PhoneTab>('mapa')
  const [ride, setRide] = useState('Só ida')
  const [reaction, setReaction] = useState('')
  const [partnerForm, setPartnerForm] = useState(false)
  const [driverForm, setDriverForm] = useState(false)
  const event = useMemo(() => experiences.find((item) => item.category === category) ?? experiences[0], [category])

  function askWill() {
    const q = query.toLowerCase()
    if (q.includes('infantil') || q.includes('criança') || q.includes('kids')) setCategory('Ambiente infantil')
    else if (q.includes('música') || q.includes('musica') || q.includes('show')) setCategory('Musica ao vivo')
    else if (q.includes('comida') || q.includes('restaurante') || q.includes('gastronomia')) setCategory('Gastronomia')
    else if (q.includes('cultura') || q.includes('teatro')) setCategory('Cultural')
    else if (q.includes('relax') || q.includes('tranquilo')) setCategory('Modo Relax')
    else setCategory('Bombando')
    setTab('evento')
    setPage('user')
  }
  function choose(value: Category) { setCategory(value); setTab('evento'); setPage('user') }
  function baixar() { alert('Interesse registrado. No lançamento, este caminho abre a loja do aparelho.') }

  return <main className="app-shell">
    <Header page={page} setPage={setPage} baixar={baixar} />
    {page === 'home' && <section className="hero"><div className="hero-copy"><h1>Onde a cidade <span>pulsa agora.</span></h1><p>Descubra o que está rolando em tempo real, veja lotação, cardápio, bebidas, combos, promoções e programe sua ida, sua volta ou sua ida + volta em uma experiência bonita, simples e pronta para virar hábito.</p><p className="subcopy">PulseAí não mostra só onde é hoje. Ele mostra onde a vida urbana realmente acontece — e te leva até lá.</p><div className="actions"><button className="primary" onClick={() => setPage('user')}>Explorar hoje</button><button className="secondary" onClick={baixar}>Quero baixar</button><button className="ghost" onClick={askWill}>Perguntar ao Will</button></div><div className="stats"><article><strong>&lt; 4 min</strong><small>para decidir onde ir com confiança</small></article><article><strong>5%+</strong><small>de cashback e pontos por check-in</small></article><article><strong>100%</strong><small>reações coletivas, positivas e anônimas</small></article></div></div><Phone event={event} category={category} query={query} setQuery={setQuery} askWill={askWill} choose={choose} tab={tab} setTab={setTab} ride={ride} setRide={setRide} reaction={reaction} setReaction={setReaction} /></section>}
    {page === 'user' && <UserPage setPage={setPage} baixar={baixar} />}
    {page === 'business' && <BusinessPage open={partnerForm} setOpen={setPartnerForm} />}
    {page === 'driver' && <DriverPage open={driverForm} setOpen={setDriverForm} />}
    {page === 'admin' && <AdminPage />}
  </main>
}

function Header({ page, setPage, baixar }: { page: Page; setPage: (p: Page) => void; baixar: () => void }) {
  return <header className="topbar"><button className="brand" onClick={() => setPage('home')}><span className="logo" /><strong>PulseAí</strong></button><nav><button className={page === 'user' ? 'nav-active' : ''} onClick={() => setPage('user')}>Para quem sai</button><button className={page === 'business' ? 'nav-active' : ''} onClick={() => setPage('business')}>Para negócios</button><button className={page === 'driver' ? 'nav-active' : ''} onClick={() => setPage('driver')}>Cadastro de motorista</button><button className={page === 'admin' ? 'nav-active' : ''} onClick={() => setPage('admin')}>Admin 🔒</button><button className="download-top" onClick={baixar}>Quero baixar</button></nav></header>
}

function Phone({ event, category, query, setQuery, askWill, choose, tab, setTab, ride, setRide, reaction, setReaction }: { event: Experience; category: Category; query: string; setQuery: (v: string) => void; askWill: () => void; choose: (v: Category) => void; tab: PhoneTab; setTab: (v: PhoneTab) => void; ride: string; setRide: (v: string) => void; reaction: string; setReaction: (v: string) => void }) {
  const [panel, setPanel] = useState(false)
  function go(next: PhoneTab) { setPanel(false); setTab(next) }
  return <aside className="phone"><div className="phone-inner"><div className="phone-top"><strong>PulseAí</strong><button className="menu-icon" onClick={() => setPanel(true)} aria-label="Abrir painel">☰</button></div><div className="phone-view">{panel && <div className="quick-panel"><h3>Painel <span>pulsa agora.</span></h3><button onClick={() => go('mapa')}>🔎 Descobrir agora</button><button onClick={() => go('evento')}>🎟️ Evento em destaque</button><button onClick={() => go('transporte')}>🚘 Programar transporte</button><button onClick={() => { setPanel(false); askWill() }}>💬 Falar com Will</button><button onClick={() => go('agenda')}>📅 Minha agenda</button><button onClick={() => go('perfil')}>👤 Meu perfil</button><button onClick={() => go('beneficios')}>✨ Pulse+ benefícios</button><button onClick={() => setPanel(false)}>Fechar painel</button></div>}
    {tab === 'mapa' && <section className="phone-section"><div className="intro-card"><small>Onde a cidade</small><span>pulsa agora.</span><b>Descubra o que está rolando em tempo real</b></div><div className="search phone-search"><span>🔎</span><input value={query} onChange={(e) => setQuery(e.target.value)} /><button onClick={() => setQuery('')}>×</button><button onClick={askWill}>🔎</button></div><div className="category-grid">{categories.map((cat) => <button key={cat} className={cat === category ? 'active' : ''} onClick={() => choose(cat)}><span>{categoryIcon[cat]}</span>{cat}</button>)}</div><div className="mini-map"><i className="pin pin-a" /><i className="pin pin-b" /><i className="pin pin-c" /><i className="pin pin-d" /><small>Bombando agora</small></div><div className="row-title"><strong>Acontecendo agora</strong><small>{event.distance}</small></div><div className="will-card"><b>Will recomenda</b><p>{event.title} porque tem {event.vibe.toLowerCase()}, cardápio publicado e boa movimentação.</p></div></section>}
    {tab === 'evento' && <section className="phone-section"><div className="photo-card" style={{ background: event.imageGradient }}><span>{event.schedule}</span></div><h3>{event.title}</h3><p>{event.description}</p><div className="phone-metrics"><article><small>Lotação</small><b>{event.crowd}%</b></article><article><small>Vibe</small><b>{event.vibe}</b></article><article><small>Cashback</small><b>{event.cashback}%</b></article><article><small>Check-ins</small><b>{event.checkins}</b></article></div><h4>Cardápio, combos e bebidas</h4><div className="phone-menu">{event.menu.map((item) => <button key={item.id} onClick={() => alert(`${item.name} — ${item.price}\n${item.detail}`)}><span>{item.emoji}</span><b>{item.name}</b><em>{item.price}</em></button>)}</div><button className="primary full" onClick={() => alert('Voucher gerado e salvo na agenda PulseAí.')}>Comprar combo / reservar</button><h4>Reagir à vibe</h4><div className="reaction-list">{reactions.map((item) => <button key={item} className={reaction === item ? 'active' : ''} onClick={() => setReaction(item)}>{item}</button>)}</div><button className="secondary full" onClick={() => alert(reaction ? `Reação enviada: ${reaction}` : 'Escolha uma reação antes de enviar.')}>Enviar reação</button></section>}
    {tab === 'transporte' && <section className="phone-section"><div className="will-card"><b>Seu plano de mobilidade</b><p>Escolha só ida, só volta ou ida + volta com geolocalização e confirmação.</p></div><div className="ride-options">{['Só ida', 'Só volta', 'Ida + volta'].map((item) => <button key={item} className={ride === item ? 'active' : ''} onClick={() => setRide(item)}>{item}</button>)}</div><div className="will-card"><b>Resumo da solicitação</b><p>Origem: minha localização. Destino: {event.title}. Tipo: {ride}. Status: aguardando motorista.</p></div><button className="primary full" onClick={() => alert(`Corrida solicitada: ${ride}. Motoristas próximos serão notificados.`)}>Solicitar corrida</button></section>}
    {tab === 'perfil' && <section className="phone-section"><div className="profile-card"><div className="avatar">W</div><h3>Will</h3><p>Perfil privado com nome, telefone, endereço residencial, preferências, pontos e histórico.</p></div><div className="phone-metrics two"><article><small>Pontos</small><b>320</b></article><article><small>Cashback</small><b>R$ 18</b></article></div></section>}
    {tab === 'agenda' && <section className="phone-section"><div className="will-card"><b>Minha agenda</b><p>Reservas, vouchers, eventos salvos e transportes programados aparecem aqui.</p></div></section>}
    {tab === 'beneficios' && <section className="phone-section"><div className="will-card"><b>Pulse+ benefícios</b><p>Cashback, pontos, prioridade em combos e campanhas exclusivas.</p></div></section>}</div><div className="phone-tabs"><button className={tab === 'mapa' ? 'tab-on' : ''} onClick={() => setTab('mapa')}><span>🗺️</span>Mapa</button><button className={tab === 'evento' ? 'tab-on' : ''} onClick={() => setTab('evento')}><span>🎟️</span>Evento</button><button className={tab === 'transporte' ? 'tab-on' : ''} onClick={() => setTab('transporte')}><span>🚘</span>Transporte</button><button className={tab === 'perfil' ? 'tab-on' : ''} onClick={() => setTab('perfil')}><span>👤</span>Perfil</button></div></div></aside>
}

function UserPage({ setPage, baixar }: { setPage: (p: Page) => void; baixar: () => void }) { return <PublicSection eyebrow="Para quem sai" title={<><span>Descubra mais rápido.</span> Escolha melhor.<br />Chegue mais fácil.</>} text="O app responde às dores levantadas na validação: saber o que está acontecendo agora, filtrar por música, ambiente e vibe, ver lotação estimada, cardápio, promoções, combos, compra antecipada e transporte pelo próprio app." cards={[['🗺️','Mapa como tela principal','O usuário abre o app e vê a cidade acontecendo em tempo real, com locais próximos e recomendações do Will.'],['🎟️','Evento completo','Foto publicada pelo estabelecimento, detalhes, lotação, cardápio, bebidas, combos, cashback e voucher.'],['🚘','Transporte flexível','O usuário pode solicitar só ida, só volta ou ida + volta, com geolocalização e confirmação.']]} ctaTitle="Baixar o app agora" ctaText="Encontrar algo interessante em poucos minutos, com oferta real, desconto real e a sensação de que agora eu sei para onde ir." ctaLabel="Quero baixar" onCta={baixar} secondaryLabel="Ver negócios" onSecondary={() => setPage('business')} /> }
function BusinessPage({ open, setOpen }: { open: boolean; setOpen: (v: boolean) => void }) { const [f, setF] = useState<PartnerForm>(() => getLocal('partner', { name: '', category: '', instagram: '', address: '', phone: '' })); return <><PublicSection eyebrow="Para negócios" title={<>Pare de depender só de stories.<br /><span>Comece a vender com dados.</span></>} text="Para bares, restaurantes, casas de show e produtores, o PulseAí entrega visibilidade geolocalizada, publicação autônoma, combos, cardápio, métricas reais, notificações e automações com WhatsApp e Instagram." cards={[['📍','Apareça para quem está perto','Seu evento surge para quem está na cidade, com interesse compatível e pronto para decidir.'],['📊','Saiba quantos viram','Visualizações, salvamentos, cliques, check-ins, vouchers, vendas, conversão e reações do público.'],['💬','Automatize a divulgação','Confirmações por WhatsApp, lembretes, relatório semanal e sugestões de post para Instagram.']]} ctaTitle="Seu evento merece mais do que alcance. Merece conversão." ctaText="Publique, apareça, venda, acompanhe e cresça com autonomia." ctaLabel="Quero cadastrar meu negócio" onCta={() => setOpen(true)} />{open && <FormPanel title="Cadastro de negócio / produtor" onClose={() => setOpen(false)} onSave={() => { saveLocal('partner', f); alert('Cadastro de negócio salvo no MVP.') }} fields={<><input placeholder="Nome do negócio" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} /><input placeholder="Categoria" value={f.category} onChange={(e) => setF({ ...f, category: e.target.value })} /><input placeholder="Instagram" value={f.instagram} onChange={(e) => setF({ ...f, instagram: e.target.value })} /><input placeholder="Endereço" value={f.address} onChange={(e) => setF({ ...f, address: e.target.value })} /><input placeholder="Telefone / WhatsApp" value={f.phone} onChange={(e) => setF({ ...f, phone: e.target.value })} /></>} />}</> }
function DriverPage({ open, setOpen }: { open: boolean; setOpen: (v: boolean) => void }) { const [f, setF] = useState<DriverForm>(() => getLocal('driver', { name: '', phone: '', vehicle: 'Carro', plate: '', city: '' })); return <><PublicSection eyebrow="Cadastro de motorista" title={<>Corridas conectadas à <span>movimentação da cidade.</span></>} text="Motoristas de carro e moto podem compor a frente de mobilidade do PulseAí, recebendo solicitações ligadas aos eventos, bares, restaurantes e experiências da cidade." cards={[['🚘','Carro ou moto','Cadastro de condutor, veículo, cidade, documentos, horários disponíveis e aprovação do perfil.'],['📍','Geolocalização','Corridas com origem, destino, tipo de solicitação, status, rota e acompanhamento da operação.']]} ctaTitle="Quer dirigir com o PulseAí?" ctaText="Entre no pré-cadastro de motoristas para participar da futura operação de mobilidade." ctaLabel="Quero me cadastrar como motorista" onCta={() => setOpen(true)} />{open && <FormPanel title="Pré-cadastro de motorista" onClose={() => setOpen(false)} onSave={() => { saveLocal('driver', f); alert('Cadastro de motorista salvo no MVP.') }} fields={<><input placeholder="Nome completo" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} /><input placeholder="Telefone / WhatsApp" value={f.phone} onChange={(e) => setF({ ...f, phone: e.target.value })} /><select value={f.vehicle} onChange={(e) => setF({ ...f, vehicle: e.target.value })}><option>Carro</option><option>Moto</option></select><input placeholder="Placa" value={f.plate} onChange={(e) => setF({ ...f, plate: e.target.value })} /><input placeholder="Cidade" value={f.city} onChange={(e) => setF({ ...f, city: e.target.value })} /></>} />}</> }
function PublicSection({ eyebrow, title, text, cards, ctaTitle, ctaText, ctaLabel, onCta, secondaryLabel, onSecondary }: { eyebrow: string; title: ReactNode; text: string; cards: string[][]; ctaTitle: string; ctaText: string; ctaLabel: string; onCta: () => void; secondaryLabel?: string; onSecondary?: () => void }) { return <section className="public-section"><span className="pill">{eyebrow}</span><h2>{title}</h2><p>{text}</p><div className="public-cards">{cards.map(([icon, cardTitle, cardText]) => <article key={cardTitle}><span>{icon}</span><h3>{cardTitle}</h3><p>{cardText}</p></article>)}</div><div className="cta-box"><h3>{ctaTitle}</h3><p>{ctaText}</p><button className="secondary" onClick={onCta}>{ctaLabel}</button>{secondaryLabel && <button className="ghost" onClick={onSecondary}>{secondaryLabel}</button>}</div></section> }
function FormPanel({ title, fields, onSave, onClose }: { title: string; fields: ReactNode; onSave: () => void; onClose: () => void }) { return <section className="form-panel"><h2>{title}</h2><div className="form-grid">{fields}</div><div className="actions"><button className="primary" onClick={onSave}>Salvar pré-cadastro</button><button className="ghost" onClick={onClose}>Fechar</button></div></section> }
function AdminPage() { const [ok, setOk] = useState(false); const [pass, setPass] = useState(''); if (!ok) return <section className="admin-lock"><span className="pill">Admin 🔒</span><h2>Controle restrito da plataforma.</h2><p>Área do criador para acompanhar usuários, negócios, motoristas, eventos, aprovações, receita e expansão.</p><input type="password" placeholder="Senha do administrador" value={pass} onChange={(e) => setPass(e.target.value)} /><button className="secondary" onClick={() => pass ? setOk(true) : alert('Digite a senha para simular o acesso.')}>Entrar no painel</button></section>; return <section className="admin-dashboard"><span className="pill">Admin liberado</span><h2>Painel de comando PulseAí</h2><div className="dashboard-grid"><article><small>Usuários</small><strong>226</strong></article><article><small>Negócios</small><strong>18</strong></article><article><small>Motoristas</small><strong>34</strong></article><article><small>Eventos ativos</small><strong>12</strong></article><article><small>Vouchers</small><strong>42</strong></article><article><small>Conversão</small><strong>18%</strong></article></div><div className="public-cards"><article><span>✅</span><h3>Aprovações</h3><p>Validar estabelecimentos, produtores, motoristas e eventos.</p></article><article><span>🧭</span><h3>Operação em tempo real</h3><p>Check-ins, transportes, mapa de calor e denúncias.</p></article><article><span>📈</span><h3>Receita e expansão</h3><p>Planos, taxas, add-ons, cidades e campanhas.</p></article></div></section> }
